# Generated by Django 4.2 on 2023-04-24 20:34

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hook',
            field=markdownx.models.MarkdownxField(default=1),
            preserve_default=False,
        ),
    ]
