# Generated by Django 4.2 on 2023-04-04 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_file_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hook',
            field=models.TextField(null=True),
        ),
    ]
